module.exports = { companyList: 
    [
        'Apple',
        'Ford Motor Company',
        'Intuit',
        'Andersen Tax',
        'AT&T',
        'The Goddard School',
        'Atticus',
        'Bellco Credit Union',
        'Best Buy',
        'Carvana',
        'Estee Lauder',
        'HCA Healthcare',
        'AlloSource',
        'Five Guys Enterprises',
        'Freddie Mac',
        'GEICO',
        'Bon Secours Mercy Health',
        'Capital One',
        'Carhartt',
        'Chegg',
        'Chipotle',
        'ChowNow',
        'Commonbond',
        'Fidelity Investments',
        'Connelly Partners',
        'Live Nation Entertainment',
        'Lockheed Martin',
        'Penguin Random House',
        "Lowe's",
        'Mclaren Health Care',
        'MidWestOne Bank',
        'Natixis',
        'Crew Carwash',
        'CSAA Insurance Group',
        'Deloitte',
        'Discover Financial Services',
        'Disney',
        'Inova Health',
        'Easterseals NH',
        'Google',
        'Tyson Foods',
        'Guild Education',
        'Herschend Enterprises',
        'Honeywell',
        'Hulu',
        'JPMorgan Chase & Co.',
        'Kaiser Permanente',
        'LendEDU',
        'New York Life Insurance Company',
        'Noodles & Company',
        'NVIDIA',
        "Papa John's",
        'Peloton',
        'Pepsico',
        'Powertex Group',
        'Public Prep',
        'Pure Insurance',
        'PwC',
        'Rock Family of Companies',
        'RubiconMD',
        'Shipt',
        'SoFi',
        "Sotheby's",
        'Staples',
        'Starbucks',
        'Sunrun',
        'Taco Bell',
        'Target',
        'Teachable',
        'The Home Depot',
        'The U.S. Government',
        'Anthem, Inc.',
        'Unilever',
        'Unqork',
        'UKG',
        'Abbott',
        'Aetna, A CVS Company',
        'Ally Financial',
        'Amazon',
        'American Family Insurance',
        'First Republic Bank',
        'Walmart',
        'Terminix',
        'Waste Management',
        'Weedmaps'
      ]
    
}